apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: docker.io/nexweb1/sample:76b8dd9ae41a4167b9400ac8badc08c9166be724
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

